apiVersion: v1
kind: Service
metadata:
  name: {{ include "syslog.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "syslog.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: syslog
      protocol: UDP
      name: syslog
  selector:
    app.kubernetes.io/name: {{ include "syslog.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
