{{ if .Values.sftp.enabled }}
{{- if not .Values.sftp.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sftp-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-sftp
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  USER_NAME: {{ .Values.sftp.username | quote }}
  USER_PASSWORD: {{ .Values.sftp.password | quote }}
{{- end }}
{{ end }}
