{{- if .Values.sftp.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-tcp-services
  labels:
    app.kubernetes.io/name: haproxy-ingress
    role: tcp-services
data:
  "22": "{{ .Release.Namespace }}/sftp-service:22"
  {{- if .Values.syslog.enabled }}
  "514": "{{ .Release.Namespace }}/sftp-service:514"
  {{- end }}
{{- end }}
