#  Deploying Call Telemetry with HAProxy Ingress

# Ingress Controller Configuration
ingress-controller:
  # Type of ingress controller to use
  type: haproxy
  # Class name for the ingress controller
  class: haproxy-{{ .Release.Namespace }}
  # Controller value for the ingress class
  controllerValue: "haproxy.io/ingress-{{ .Release.Namespace }}"
  # Selector labels for the ingress controller
  selector:
    instance: "haproxy-ingress"
    name: haproxy-ingress
  controller:
    # Create a test-specific ClusterRole with a unique name
    clusterRole:
      create: true
      name: "haproxy-ingress-{{ .Release.Namespace }}"
    # Use a unique IngressClass name for testing
    ingressClassResource:
      name: haproxy-{{ .Release.Namespace }}
      enabled: true
      default: false
      controllerValue: "haproxy.io/ingress-{{ .Release.Namespace }}"
    # Set a unique name for other cluster-wide resources
    electionID: haproxy-ingress-leader-{{ .Release.Namespace }}
    # Add environment label
    podLabels:
      environment: test
    tcp:
      22: "{{ .Release.Namespace }}/admin-internal-service:3022"
      514: "{{ .Release.Namespace }}/syslog-internal-service:514"

# Load Balancer Common Configuration
loadBalancer:
  # Ingress class annotation - used by all load balancers
  ingressClass: haproxy-{{ .Release.Namespace }}
  # Common annotations for all load balancers
  annotations:
    kubernetes.io/ingress.class: haproxy-{{ .Release.Namespace }}
    # Selector for the ingress controller pods
    ingress.kubernetes.io/selector-instance: "haproxy-ingress"
    ingress.kubernetes.io/selector-name: haproxy-ingress

### Load Balancer Configuration ###
# Primary API Load Balancer
primary_api:
  createLoadBalancer: true
  advertiseL2MetalLb: true
  metal_ip_address: "192.168.123.225"

# Secondary API Load Balancer
secondary_api:
  createLoadBalancer: true
  advertiseL2MetalLb: true
  metal_ip_address: "192.168.123.216"

# Admin API Load Balancer - Management API
admin_api:
  createLoadBalancer: true
  advertiseL2MetalLb: true
  metal_ip_address: "192.168.123.217"
### /Load Balancer Configuration ###

# Enable SFTP ports on load balancer
sftp:
  enabled: true

# Enable Syslog ports on load balancer
syslog:
  enabled: true

