apiVersion: v1
kind: Service
metadata:
  name: teams-auth-service
  labels:
    app.kubernetes.io/name: teams-auth-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app.kubernetes.io/name: {{ include "azure-msal-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
