apiVersion: v1
appVersion: 0.8.5-rc19
description: Call Telemetry for Cisco Callmanager
home: https://calltelemetry.com/
icon: https://calltelemetry.com/logo.png
maintainers:
- email: support@calltelemetry.com
  name: Call Telemetry LLC
name: api
version: 0.11.12
