apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blackbox.labels" . | nindent 4 }}
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: {{ .Values.config.http2xx.timeout }}
        http:
          preferred_ip_protocol: {{ .Values.config.http2xx.preferredIpProtocol }}
          valid_status_codes: []
