image:
  repository: quay.io/prometheus/blackbox-exporter
  tag: v0.28.0
  pullPolicy: IfNotPresent

service:
  port: 9115

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

config:
  http2xx:
    timeout: 5s
    preferredIpProtocol: ip4

nodeSelector: {}
tolerations: []
affinity: {}
