---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-traceroute-service"
  labels:
    app: "{{ .Release.Name }}-traceroute-service"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-traceroute-service"
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 70%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-traceroute-service"
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 2
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 2
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: "{{ .Release.Name }}-traceroute"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            - name: NATS_HOSTNAME
              value: "{{ .Values.nats.server }}"
