apiVersion: v2
name: vue-web
description: CallTelemetry Vue/Quasar Web Portal - Caddy-served SPA
type: application
version: 1.0.0
appVersion: "0.8.5"
home: https://calltelemetry.com/
maintainers:
  - email: support@calltelemetry.com
    name: Call Telemetry LLC
