apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seaweedfs.fullname" . }}-s3-config
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
data:
  s3.json: |
    {
      "identities": [
        {
          "name": "admin",
          "credentials": [
            {
              "accessKey": {{ .Values.auth.accessKey | quote }},
              "secretKey": {{ .Values.auth.secretKey | quote }}
            }
          ],
          "actions": ["Admin", "Read", "Write", "List", "Tagging"]
        }
      ]
    }
