apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seaweedfs.fullname" . }}
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "seaweedfs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "seaweedfs.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - weed
            - server
            - -s3
            - -s3.port={{ .Values.service.s3Port }}
            - -s3.config=/etc/seaweedfs/s3.json
            - -master.volumeSizeLimitMB={{ .Values.masterVolumeSizeLimitMB }}
          ports:
            - name: s3
              containerPort: {{ .Values.service.s3Port }}
              protocol: TCP
            - name: filer
              containerPort: {{ .Values.service.filerPort }}
              protocol: TCP
            - name: master
              containerPort: {{ .Values.service.masterPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /cluster/healthz
              port: master
            initialDelaySeconds: {{ .Values.healthCheck.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /cluster/healthz
              port: master
            initialDelaySeconds: {{ .Values.healthCheck.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.readiness.periodSeconds }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: s3-config
              mountPath: /etc/seaweedfs
              readOnly: true
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-data" (include "seaweedfs.fullname" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: s3-config
          secret:
            secretName: {{ include "seaweedfs.fullname" . }}-s3-config
