{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seaweedfs.secretName" . }}
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: {{ .Values.auth.accessKey | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.auth.secretKey | quote }}
{{- end }}
