{{- if and .Values.secondary_api.createLoadBalancer .Values.secondary_api.advertiseL2MetalLb }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: secondary-ip-{{ .Release.Namespace }}
  namespace: metallb-system
spec:
  addresses:
  - {{ .Values.secondary_api.ip }}/32
  autoAssign: false
status: {}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: secondary-l2-advert-{{ .Release.Namespace }}
  namespace: metallb-system
spec:
  ipAddressPools:
  - secondary-ip-{{ .Release.Namespace }}
{{- end }}
