apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ksm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ksm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ksm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "ksm.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ksm.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: kube-state-metrics
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --port={{ .Values.service.port }}
            - --telemetry-port={{ .Values.service.telemetryPort }}
            - --resources={{ join "," .Values.collectors }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
            - name: telemetry
              containerPort: {{ .Values.service.telemetryPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: telemetry
            initialDelaySeconds: 5
            periodSeconds: 10
