apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ksm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ksm.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ksm.clusterRoleName" . }}
  labels:
    {{- include "ksm.labels" . | nindent 4 }}
rules:
  - apiGroups: [admissionregistration.k8s.io]
    resources: [mutatingwebhookconfigurations, validatingwebhookconfigurations]
    verbs: [list, watch]
  - apiGroups: [certificates.k8s.io]
    resources: [certificatesigningrequests]
    verbs: [list, watch]
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - limitranges
      - namespaces
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - replicationcontrollers
      - resourcequotas
      - services
    verbs: [list, watch]
  - apiGroups: [apps]
    resources: [daemonsets, deployments, replicasets, statefulsets]
    verbs: [list, watch]
  - apiGroups: [batch]
    resources: [cronjobs, jobs]
    verbs: [list, watch]
  - apiGroups: [discovery.k8s.io]
    resources: [endpointslices]
    verbs: [list, watch]
  - apiGroups: [autoscaling]
    resources: [horizontalpodautoscalers]
    verbs: [list, watch]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses, networkpolicies]
    verbs: [list, watch]
  - apiGroups: [policy]
    resources: [poddisruptionbudgets]
    verbs: [list, watch]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses, volumeattachments]
    verbs: [list, watch]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ksm.clusterRoleName" . }}
  labels:
    {{- include "ksm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ksm.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ksm.fullname" . }}
    namespace: {{ .Release.Namespace }}
