apiVersion: v1
kind: Service
metadata:
  name: {{ include "ksm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ksm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: telemetry
      port: {{ .Values.service.telemetryPort }}
      targetPort: telemetry
  selector:
    app.kubernetes.io/name: {{ include "ksm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
