apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-echo-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  {{- if and .Values.tls.enabled (or .Values.primary_hostname .Values.secondary_hostname .Values.admin_hostname) }}
  tls:
    - hosts:
        {{- if .Values.primary_hostname }}
        - {{ .Values.primary_hostname }}
        {{- end }}
        {{- if .Values.secondary_hostname }}
        - {{ .Values.secondary_hostname }}
        {{- end }}
        {{- if .Values.admin_hostname }}
        - {{ .Values.admin_hostname }}
        {{- end }}
      {{- if .Values.tls.secretName }}
      secretName: {{ .Values.tls.secretName }}
      {{- else if .Values.primary_hostname }}
      secretName: {{ .Values.primary_hostname }}
      {{- else if .Values.secondary_hostname }}
      secretName: {{ .Values.secondary_hostname }}
      {{- else if .Values.admin_hostname }}
      secretName: {{ .Values.admin_hostname }}
      {{- end }}
  {{- end }}
  rules:
    {{- if .Values.primary_hostname }}
    - host: {{ .Values.primary_hostname }}
      http:
        paths:
        - path: /echo
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-echo-service
              port:
                number: 80
    {{- end }}
    {{- if .Values.secondary_hostname }}
    - host: {{ .Values.secondary_hostname }}
      http:
        paths:
        - path: /echo
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-echo-service
              port:
                number: 80
    {{- end }}
    {{- if .Values.admin_hostname }}
    - host: {{ .Values.admin_hostname }}
      http:
        paths:
        - path: /echo
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-echo-service
              port:
                number: 80
    {{- end }}
    {{- if .Values.enableCatchAllRoute }}
    # Catch-all route that matches any host (including IP addresses)
    - http:
        paths:
        - path: /echo
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-echo-service
              port:
                number: 80
    {{- end }}
