apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-echo-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClassName }}
    haproxy.org/load-balance: "roundrobin"
    # haproxy.org/load-balance: "leastconn"
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - host: {{ .Values.primary_hostname }}
      http:
        paths:
        - path: /echo
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-echo-service
              port:
                number: 80
    - host: {{ .Values.secondary_hostname }}
      http:
        paths:
        - path: /echo
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-echo-service
              port:
                number: 80
    - host: {{ .Values.admin_hostname }}
      http:
        paths:
        - path: /echo
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-echo-service
              port:
                number: 80
