fullnameOverride: alertmanager

config:
  emailTo: jason.barbee@gmail.com
  route:
    receiver: dashboard-email
    groupBy: ['alertname', 'namespace', 'workload']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    routes:
      - match:
          severity: critical
        receiver: critical-direct
  receivers:
    - name: dashboard-email
      emailConfigs:
        - to: jason.barbee@gmail.com
          sendResolved: true
    - name: critical-direct
      emailConfigs:
        - to: jason.barbee@gmail.com
          sendResolved: true
  smtp:
    enabled: true
    smarthost: smtp.mailgun.org:587
    from: alerts@calltelemetry.com
    authUsername: postmaster@calltelemetry.com
    existingSecret: alertmanager-mailgun
    passwordKey: smtp_password

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

persistence:
  enabled: true
  size: 1Gi
