# Values for API chart with HAProxy ingress
ingressClassName: haproxy-ct-prod

# Database configuration
db:
  useExistingSecret: true  # Set to true to use an existing secret
  existingSecretName: hippo-pguser-calltelemetry # Name of the secret containing DB credentials

# API Config
api:
  hostname: prod.calltelemetry.com
  # Example of API ingress annotations if needed
  # ingress:
  #   annotations:
  #     haproxy.org/load-balance: "roundrobin"

# Admin configuration
admin:
  api_worker: true
  hostname: prod.calltelemetry.com
  # Example of adding additional ingress annotations if needed
  # ingress:
  #   annotations:
  #     haproxy.org/ssl-redirect: "true"


# SFTP Configuration
sftp:
  enabled: true

# Syslog Configuration
syslog:
  enabled: true
