# Values for API chart with HAProxy ingress
ingressClassName: haproxy-ct-prod

# Database configuration
db:
  useExistingSecret: true  # Set to true to use an existing secret
  existingSecretName: hippo-pguser-calltelemetry # Name of the secret containing DB credentials

# API Config
api:
  hostname: prod.calltelemetry.com
  ingress:
    annotations:
      haproxy.org/load-balance: "leastconn"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      haproxy.org/ssl-redirect: "true"
  tls:
    - secretName: prod-calltelemetry-com-tls
      hosts:
        - prod.calltelemetry.com

# Admin configuration
admin:
  api_worker: true
  hostname: prod.calltelemetry.com
  ingress:
    annotations:
      haproxy.org/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - secretName: prod-calltelemetry-com-tls
      hosts:
        - prod.calltelemetry.com


# SFTP Configuration
sftp:
  enabled: true

# Syslog Configuration
syslog:
  enabled: true
