# API Appliance Values
# Single-node K3s appliance with SFTP and syslog enabled
ingressClassName: haproxy-ct

# Database configuration
db:
  useExistingSecret: true
  existingSecretName: postgresql-app-credentials
  values:
    db_ssl_enabled: false

# API Config
api:
  hostname: calltelemetry.local
  image: calltelemetry/web
  tag: 0.8.6-rc140
  imagePullPolicy: IfNotPresent
  replicas: 1
  ingress:
    annotations:
      kubernetes.io/ingress.class: "haproxy-ct"
      haproxy.org/load-balance: "leastconn"

# Admin configuration
admin:
  api_worker: true
  hostname: calltelemetry.local
  image: calltelemetry/web
  tag: 0.8.6-rc140
  imagePullPolicy: IfNotPresent
  ingress:
    annotations:
      kubernetes.io/ingress.class: "haproxy-ct"
      haproxy.org/load-balance: "roundrobin"

# SFTP Configuration
sftp:
  enabled: true

# Syslog Configuration
syslog:
  enabled: true
