# Values for API chart with HAProxy ingress
ingressClassName: haproxy-ct-dev

# Database configuration
db:
  useExistingSecret: true # Set to true to use an existing secret
  existingSecretName: hippo-pguser-calltelemetry # Name of the secret containing DB credentials

# API Config
api:
  hostname: ct-dev.k8s.orb.local
  image: calltelemetry/web
  tag: 0.8.5-rc25
  imagePullPolicy: Always
  replicas: 2
  # Example of API ingress annotations
  ingress:
    annotations:
      kubernetes.io/ingress.class: "haproxy-ct-dev"
      haproxy.org/load-balance: "leastconn"

# Admin configuration
admin:
  api_worker: true
  # Only override hostname if different from default
  hostname: ct-dev.k8s.orb.local
  image: calltelemetry/web
  tag: 0.8.5-rc25
  imagePullPolicy: Always
  # Admin ingress annotations
  ingress:
    annotations:
      kubernetes.io/ingress.class: "haproxy-ct-dev"
      haproxy.org/load-balance: "roundrobin"

# SFTP Configuration
sftp:
  enabled: true
  # Only override if different from defaults

# Syslog Configuration
syslog:
  enabled: true
  # Other syslog settings use defaults
