# Values for echo chart with HAProxy ingress in ct-dev namespace
ingressClassName: haproxy-ct-dev

# Hostnames for the ingress rules
primary_hostname: ct-dev.k8s.orb.local
secondary_hostname: ct-dev.k8s.orb.local
admin_hostname: ct-dev.k8s.orb.local

# TLS configuration
tls:
  enabled: true
  secretName: ct-dev.k8s.orb.local

# Ingress annotations configuration
ingress:
  annotations:
    kubernetes.io/ingress.class: "haproxy-ct-dev"
    haproxy.org/load-balance: "roundrobin"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Add additional annotations as needed
    # Example: haproxy.org/timeout-client: "30s"
