# Values for echo chart with HAProxy ingress in ct-dev namespace
ingressClassName: haproxy-ct-dev

# Hostnames for the ingress rules
primary_hostname: dev.calltelemetry.com
secondary_hostname: dev.calltelemetry.com
admin_hostname: dev.calltelemetry.com

# Ingress annotations configuration
ingress:
  annotations:
    kubernetes.io/ingress.class: "haproxy-ct-dev"
    haproxy.org/load-balance: "roundrobin"
    # Add additional annotations as needed
    # Example: haproxy.org/timeout-client: "30s"
