fullnameOverride: grafana

image:
  repository: grafana/grafana
  tag: 13.1.0

admin:
  existingSecret: grafana-admin

authProxy:
  enabled: true
  headerName: X-Webauth-User
  headerProperty: email
  autoSignUp: true

datasources:
  prometheus:
    enabled: true
    url: http://prometheus.observability.svc.cluster.local:9090
  alertmanager:
    enabled: true
    url: http://alertmanager.observability.svc.cluster.local:9093

persistence:
  enabled: true
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
