# Namespace-specific RBAC resources for HAProxy ingress controller
# This template will be used with the namespace value replaced

# ServiceAccount for the namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy-ingress
  namespace: NAMESPACE_PLACEHOLDER

---
# ClusterRoleBinding for the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: haproxy-ingress-crb-NAMESPACE_PLACEHOLDER
subjects:
- kind: ServiceAccount
  name: haproxy-ingress
  namespace: NAMESPACE_PLACEHOLDER
roleRef:
  kind: ClusterRole
  name: haproxy-cluster-role-devops
  apiGroup: rbac.authorization.k8s.io
