# Shared ClusterRole with permissions needed by HAProxy ingress controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-cluster-role-devops
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - endpoints
  - nodes
  - pods
  - services
  - namespaces
  - events
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
- apiGroups: ["networking.k8s.io"]
  resources:
  - ingresses
  - ingressclasses
  - ingresses/status
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - patch
- apiGroups: ["extensions"]
  resources:
  - ingresses
  - ingresses/status
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - patch
- apiGroups: ["discovery.k8s.io"]
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
