fullnameOverride: prometheus

image:
  repository: prom/prometheus
  tag: v3.11.0

config:
  scrapeInterval: 15s
  evaluationInterval: 15s
  retention: 15d

scrapeTargets:
  otelCollector:
    enabled: false
    namespace: ct-prod
  nats:
    enabled: false
    namespace: ct-prod
  seaweedfs:
    enabled: false
    namespace: ct-prod
  postgresql:
    enabled: false
    namespace: ct-prod
  caddy:
    enabled: false
    namespace: ct-prod
  jtapiSidecar:
    enabled: false
    namespace: ct-prod
  calltelemetry:
    enabled: false
    namespace: ct-prod
  dashboard:
    enabled: true
    service: dashapi-dash-api
    namespace: dashboard
    port: 4021
    metricsPath: /metrics
  kubeStateMetrics:
    enabled: true
    service: kube-state-metrics
    namespace: observability
    port: 8080
  nodeExporter:
    enabled: true
    namespace: observability
    service: node-exporter
    port: 9100
  kubeletCadvisor:
    enabled: true
  dashboardPublic:
    enabled: true
    service: blackbox-exporter
    namespace: observability
    port: 9115
    target: https://dash.calltelemetry.com/health/ready

alerting:
  enabled: true
  alertmanagerPort: 9093

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 2Gi
