# Values for Traceroute chart in development environment
replicaCount: 1

image:
  repository: calltelemetry/traceroute
  tag: 0.8.5-rc23
  pullPolicy: Always

resources:
  requests:
    cpu: "256m"
  limits:
    cpu: 1

# NATS server configuration
nats:
  server: "nats"

# Service configuration
service:
  type: ClusterIP
  port: 4100
  targetPort: 4100

# Security context
securityContext:
  runAsUser: 0

# Termination grace period
terminationGracePeriodSeconds: 5
