# Vue Web Appliance Values
# Frontend for K3s appliance

replicaCount: 1
environment: prod
vue_web:
  image:
    repository: calltelemetry/vue
    tag: 0.8.6-rc143
    pullPolicy: IfNotPresent
  port: 8080
  LogLevel: "INFO"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  ingressClassName: haproxy-ct
  annotations:
    kubernetes.io/ingress.class: "haproxy-ct"
    haproxy.org/cookie-strategy: "insert"
    haproxy.org/cookie-name: "CTSESSIONID"
  hosts:
    - host: calltelemetry.local
      paths: ["/", "/#"]
  tls: []

resources: {}
