apiVersion: v1
kind: Service
metadata:
  name: traceroute
  labels:
    app: "{{ .Release.Name }}-traceroute-service"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: "{{ .Release.Name }}-traceroute-service"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: api
