{{- if eq (index .Values "ingress-controller" "type") "haproxy" }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: haproxy-{{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ index .Values "ingress-controller" "selector" "name" }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
spec:
  controller: haproxy.io/ingress-{{ .Release.Namespace }}
{{- end }}
