{{- if .Values.primary_api.createLoadBalancer }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-primary-api-external-lb
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-primary-api
  annotations:
    {{- if .Values.primary_api.advertiseL2MetalLb }}
    metallb.universe.tf/address-pool: primary-ip-{{ .Release.Namespace }}
    {{- end }}
    {{- with .Values.loadBalancer.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.primary_api.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    {{- include "ingress.controllerSelector" . | nindent 4 }}
  ports:
    - port: {{ .Values.primary_api.port }}
      targetPort: 80
      protocol: TCP
      name: web
    - port: {{ .Values.primary_api.https_port }}
      targetPort: 443
      protocol: TCP
      name: https
    {{- if .Values.syslog.enabled }}
    - port: {{ .Values.syslog.tcp_port }}
      targetPort: {{ .Values.syslog.targetPort }}
      protocol: TCP
      name: syslog-tcp
    {{- end }}
    {{- if .Values.sftp.enabled }}
    - port: {{ .Values.sftp.port }}
      targetPort: {{ .Values.sftp.targetPort }}
      protocol: TCP
      name: sftp
    {{- end }}
{{- end }}
