{{- if .Values.secondary_api.createLoadBalancer }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-secondary-api-external-lb
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-secondary-api
  annotations:
    {{- if .Values.secondary_api.advertiseL2MetalLb }}
    metallb.universe.tf/address-pool: secondary-ip-{{ .Release.Namespace }}
    {{- end }}
    {{- with .Values.loadBalancer.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.secondary_api.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    {{- include "ingress.controllerSelector" . | nindent 4 }}
  ports:
    # Standard HTTP/HTTPS ports
    - port: {{ .Values.ports.http }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: {{ .Values.ports.https }}
      targetPort: 443
      protocol: TCP
      name: https
    # TCP services (SFTP, Syslog, etc.)
    {{- range $port, $service := .Values.tcpServices }}
    - port: {{ $port | int }}
      targetPort: {{ $service.targetPort }}
      protocol: TCP
      name: {{ $service.serviceName | replace "-service" "" }}
    {{- end }}
{{- end }}
