apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-tcp-services
  labels:
    app.kubernetes.io/name: haproxy-{{ .Release.Namespace }}
    role: tcp-services
data:
{{- if .Values.tcpServices }}
{{- range $key, $value := .Values.tcpServices }}
  "{{ $key }}": "{{ $.Release.Namespace }}/{{ $value.serviceName }}:{{ $value.targetPort }}"
{{- end }}
{{- else }}
  # Default empty data to ensure valid YAML
  "_comment": "No TCP services configured"
{{- end }}
