{{- if and .Values.persistence.jars.enabled (not .Values.persistence.jars.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jtapi-sidecar.fullname" . }}-jars
  labels:
    {{- include "jtapi-sidecar.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.jars.accessMode }}
  {{- if .Values.persistence.jars.storageClass }}
  storageClassName: {{ .Values.persistence.jars.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.jars.size }}
{{- end }}
---
{{- if and .Values.persistence.audio.enabled (not .Values.persistence.audio.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jtapi-sidecar.fullname" . }}-audio
  labels:
    {{- include "jtapi-sidecar.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.audio.accessMode }}
  {{- if .Values.persistence.audio.storageClass }}
  storageClassName: {{ .Values.persistence.audio.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.audio.size }}
{{- end }}
