{{- if not .Values.cucm.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jtapi-sidecar.cucmSecretName" . }}
  labels:
    {{- include "jtapi-sidecar.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.cucm.secretKeys.host }}: {{ .Values.cucm.host | quote }}
  {{ .Values.cucm.secretKeys.user }}: {{ .Values.cucm.user | quote }}
  {{ .Values.cucm.secretKeys.password }}: {{ .Values.cucm.password | quote }}
{{- end }}
---
{{- if and .Values.websocket.enabled (not .Values.websocket.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jtapi-sidecar.websocketSecretName" . }}
  labels:
    {{- include "jtapi-sidecar.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.websocket.secretKey }}: {{ .Values.websocket.authToken | quote }}
{{- end }}
