image:
  repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
  tag: v2.18.0
  pullPolicy: IfNotPresent

service:
  port: 8080
  telemetryPort: 8081

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
