name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'helm/charts/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Package and Publish Charts
        uses: helm/chart-releaser-action@419f3267f205afd4639d2eb12a64e911088a5d3d # v1
        with:
          charts_dir: helm/charts
          config: helm/cr.yaml
          skip_existing: true
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
