name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'helm/charts/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and Publish Charts
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: helm/charts
          config: helm/cr.yaml
          skip_existing: true
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
